import "./SeatsAllotmentImax.css";

const seatAllotArray = [
  {
    disabled: true,
    noSeat: true,
  },
];

function SeatsAllotmentImax() {
  return (
    <div className="seatAllotmentPage_Wrapper">
      <div className="TotalSeatsAllotment">
        {/* Royal Rs.500 */}
        <div className="Royal firstChild">
          <div className="child1">
            <div className="seatRowName">A</div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat disableSeat">1</div>
            <div className="seat disableSeat">2</div>
            <div className="seat disableSeat">3</div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>

            <div className="seatRowName">B</div>
            <div className="seat nbSeat"></div>
            <div className="seat">1</div>
            <div className="seat disableSeat">2</div>
            <div className="seat disableSeat">3</div>
            <div className="seat">4</div>
            <div className="seat disableSeat">5</div>

            <div className="seat nbSeat"></div>
          </div>
          <div className="child2">
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat disableSeat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat nbSeat"></div>
            {/*  */}
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat disableSeat">6</div>
            <div className="seat disableSeat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>

            <div className="seat nbSeat"></div>
          </div>
        </div>
        {/* Club Rs.450 */}
        <div className="Club firstChild">
          <div className="child1">
            <div className="seatRowName">C</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
          </div>
          <div className="child2">
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
          </div>
        </div>
        {/* Executive Rs.400 */}
        <div className="Club firstChild">
          <div className="child1">
            <div className="seatRowName">C</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seatRowName">A</div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat nbSeat"></div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
          </div>
          <div className="child2">
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
            <div className="seat">1</div>
            <div className="seat">2</div>
            <div className="seat">3</div>
            <div className="seat">4</div>
            <div className="seat">5</div>
            <div className="seat">6</div>
            <div className="seat">7</div>
            <div className="seat">8</div>
            <div className="seat">9</div>
            <div className="seat">10</div>
            <div className="seat">11</div>
            <div className="seat">12</div>
            <div className="seat">13</div>
            <div className="seat">14</div>
          </div>
        </div>
        <div></div>
      </div>
    </div>
  );
}
export default SeatsAllotmentImax;
